# Generated by Django 2.0.3 on 2018-03-19 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surol', '0002_course_course_deadline_personal_deadline_registers_takes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_deadline',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='personal_deadline',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
